# Load DSL and Setup Up Stages
require "capistrano/setup"

# Includes default deployment tasks
require "capistrano/deploy"

require "airbrussh/capistrano"
require "sshkit/sudo"
require "capistrano/rails"
require "capistrano/cookbook"